name: Bump and Publish to npm
on:
  push:
    branches: [main]

jobs:
  build-bump-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn' # Explicitly caching Yarn

      # 1. Install dependencies using Yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # 2. Configure Git
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Bump version (This will only touch package.json since there is no package-lock)
      - name: Bump Version
        run: npm version minor -m "chore: bump version to %s [skip ci]"

      # 4. Push changes back to GitHub
      - name: Push changes
        run: git push --follow-tags

      # 5. Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
